config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors,:controllers => { registrations: 'registrations' }
	resources :patients do
		resources :reports
	end
	root 'patients#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord
	has_many :patients
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :patients
	has_many :reports
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :doctor
	belongs_to :condition
	has_many :reports
end

app/models/report.rb
class Report < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :find_patient, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_doctor!, only: [:new, :edit]
	def index 
		if params.has_key?(:condition)
			@condition_id = Condition.find_by(name: params[:condition]).id
			@patients = Patient.where(:condition_id => @condition_id).order("created_at DESC")
		elsif params.has_key?(:doctor_id)
			@patients = Patient.where(:doctor_id => params[:doctor_id]).order("created_at DESC")
		else
			@patients = Patient.all.order("created_at DESC")
		end
	end

	def show 
	end

	def new 
		@patient = current_doctor.patients.build
		@conditions = Condition.all.map{ |c| [c.name,c.id]}
	end

	def create
		@patient = current_doctor.patients.build(patient_params)
		@patient.condition_id = params[:condition_id]

		if @patient.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@conditions = Condition.all.map{ |c| [c.name,c.id]}
	end 

	def update
		@patient.condition_id = params[:condition_id]
		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end

	def destroy
		@patient.destroy
		redirect_to root_path
	end

	private
		def patient_params
			params.require(:patient).permit(:fname,:lname,:address,:dob,:bloodtype,:alergies,:condition_id)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:doctor).permit(:clinic_id,:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:doctor).permit(:clinic_id,:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :find_patient
	before_action :find_report, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_doctor!, only: [:new, :edit]
	def new
		@report = Report.new 
	end 

	def show 
	end

	def create
		@report = Report.new(report_params)
		@report.doctor_id = current_doctor.id
		@report.patient_id = @patient.id

		if @report.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @report.update(report_params)
			redirect_to patient_path(@patient)
		else 
			render 'edit'
		end
	end

	def destroy
		@report.destroy
		redirect_to patient_path(@patient)
	end

	private

		def report_params
			params.require(:report).permit(:date, :report)
		end

		def find_patient
			@patient = Patient.find(params[:patient_id])
		end

		def find_report
			@report = Report.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Smart Health Application</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<nav class="navbar navbar-default">
		  	<div class="container">
		  		<div class="navbar-header">
		  			<%= link_to "Smart Health", root_path, class: "navbar-brand" %>
		  		</div>
		  		<ul class="nav navbar-nav">
		  			<li><%= link_to "Register Doctor", new_doctor_registration_path %></li>
		  			<% if doctor_signed_in? %> 
		  				<li><%= link_to "Sign out", destroy_doctor_session_path, method: :delete %></li>
		  			<% else %> 
		  				<li><%= link_to "Login", new_doctor_session_path %></li>
		  			<% end %>
		  		</ul>

		  		<ul class="nav navbar-nav navbar-right">
		  			<li class="dropdown">
		  				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
		  					Sort by Condition<span class="caret"></span>
		  				</a>
		  				<ul class="dropdown-menu" role="menu">
		  					<% Condition.all.each do |condition| %>
		  						<li class="<%= 'active' if params[:condition] == condition.name %>">
		  							<%= link_to condition.name, patients_path(condition: condition.name), class: "link"%>
		  						</li>
		  					<% end %> 
		  				</ul>
		  			</li>
			  		<% if doctor_signed_in? %>
			  			<li><%= link_to "Your Patients", patients_path(doctor_id: current_doctor.id), class: "link"%></li>
			  		<% end %>

		  			<% if doctor_signed_in? %>
		  				<li><%= link_to "Add Patient", new_patient_path %></li>
		  			<% end %>
		  		</ul>
		  	</div>
  		</nav>
 
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= simple_form_for @patient, :html => { :multipart => true } do |f| %>
	<%= select_tag(:condition_id, options_for_select(@conditions), :prompt => "Select Condition")%>
	<%= f.input :fname, label: "First Name",:maxlength => 10 %>
	<%= f.input :lname, label: "Family Name",:maxlength => 10  %>
	<%= f.input :address, label: "Address",:maxlength => 50  %>
	<%= f.input :dob, label: "Date of Birth",:maxlength => 11  %>
	<%= f.input :bloodtype, label: "Blood Type",:maxlength => 3  %>
	<%= f.input :alergies, label: "Alergies",:maxlength => 15  %>
	<center><%= f.button :submit, :class => 'button_one'  %></center>
<% end %>

app/views/patients/edit.html.erb
<div class="container">
	<div class="edit-patient-form">
		<center><p class="new_patient_text">Edit Patient</p></center>
		<%= simple_form_for @patient, :html => { :multipart => true } do |f| %>
			<%= f.select :condition_id, @conditions %>
			<%= f.input :fname, label: "First Name" %>
			<%= f.input :lname, label: "Family Name" %>
			<%= f.input :address, label: "Address" %>
			<%= f.input :dob, label: "Date of Birth" %>
			<%= f.input :bloodtype, label: "Blood Type" %>
			<%= f.input :alergies, label: "Alergies" %>
			<center><%= f.button :submit, :class => 'button_one'  %></center>
		<% end %>
	</div>
</div>

app/views/patients/index.html.erb
<div class="index_profile_info">
	<% if doctor_signed_in? %>
		<h3>Signed in as:</h3>
		<h5>Dr. <%= current_doctor.first_name %> <%= current_doctor.last_name %></h5>
		<br>
		<h5>Clinic ID: <%= current_doctor.clinic_id %></h5>
		<br><br>
		<center><td><%= link_to "Edit Profile", edit_doctor_registration_path(current_doctor),class: "button_one" %></td></center>
	<% else %>
		<img src="/not.png" alt="Not logged in" style="display: block; margin-left: auto;margin-right: auto;" height="50" width="50"/>
		<h4 style="text-align: center; vertical-align: middle; line-height: 90px;">
			You are not signed in!
		</h4>
	<% end %>
</div>

<div class="container">	
	<div class="index-form">	
		<div class="jumbotron" style="min-height: 100px;padding: 15px;background-color:#fff;">
			<% if @patients.count ==0 %>
				<center><h3>There are no patients</h3></center>
			<% else %>
				<table class="table table-striped">
					<thead>
						<tr>
				    		<th>Name</th>
				    		<th>Blood Type</th>
				    		<th>Address</th>
				    		<th/>
				  		</tr>
				  	</thead>
				  	<tbody>
						<% @patients.each do |patient|%>
							<tr>
								<td><%= patient.fname+" "+patient.lname%></td>
								<td><%= patient.bloodtype%></td>
								<td><%= patient.address%></td>
								<td><%= link_to "View Record", patient_path(patient),class: "button_one" %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>
 

app/views/patients/new.html.erb
<div class="container">
	<div class="new-patient-form">
		<center><p class="new_patient_text">New Patient</p></center>
		<%= render 'form' %>
	</div>
</div>

app/views/patients/show.html.erb
<div class="patient_info">
	<h3><%= @patient.fname %> <%= @patient.lname %></h3>
	<h4>Condition: <%= @patient.condition.name %></h4>
	<h4><%= @patient.bloodtype %></h4>
	<h4><%= @patient.dob %></h4>
	<h4><%= @patient.address %></h4>
	<% if @patient.reports.count == 1 %>
		<h5>1 report for this patient</h5>
	<% else %>
		<h5><%= @patient.reports.count %> reports for this patient</h5>
	<% end %>
	<br>
	<%= link_to "Back", root_path,class: "button_one" %>

	<% if doctor_signed_in? %>
		<% if @patient.doctor_id == current_doctor.id %>
			<%= link_to "Edit", edit_patient_path(@patient),class: "button_one" %>
			<%= link_to "Delete", patient_path(@patient), method: :delete, data: {confirm: "Are you sure?"},class: "button_one" %>
		<% end %>
	<% end %>
</div>

<div class="patient_reports" align="center">
	<% if @patient.reports.count ==0 %>
		<center><h1>This patient has no medical reports on file</h1></center>
	<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>First Name </th>
					<th>Last Name </th>
			    	<th>Date</th>
			    	<th/>
			  	</tr>
			</thead>
			<tbody>
				<% @patient.reports.each do |report|%>
					<tr>
						<td><%= report.patient.fname %></td>
						<td><%= report.patient.lname %></td>
						<td><%= report.date %></td>
						<td><%= link_to "View Report", patient_report_path(report.patient.id,report.id),class: "button_one" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
	<% if doctor_signed_in? %>
		<% if @patient.doctor_id == current_doctor.id %>
			<%= link_to "Add Visit Report", new_patient_report_path(@patient),class: "button_one" %>
		<% end %>
	<% end %>
</div>

app/views/reports/_form.html.erb
<%= simple_form_for([@patient, @patient.reports.build]) do |f| %>
	<%= f.input :date, :input_html => {:style => 'width: 250px;height:50px;'} %>
	<%= f.input :report, :input_html => {:style => 'height:320px;'}%>
	<center><%= f.button :submit, :class => 'button_one'  %></center>
<% end %>

app/views/reports/_report.html.erb
<p><%= report.date %></p>
<h3><%= report.report %></h3>

<% if doctor_signed_in? %> 
	<% if report.doctor_id == current_doctor.id %> 
		<%= link_to "Edit", edit_patient_report_path(report.patient, report) %>
		<%= link_to "Delete", patient_report_path(report.patient, report), method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>

app/views/reports/edit.html.erb
<div class="container">
	<div class="edit-report-form">
		<center><p class="new_patient_text">Edit Report</p></center>
		<%= simple_form_for([@patient, @report]) do |f| %>
			<%= f.input :date, :input_html => {:style => 'width: 250px;height:50px;'} %>
			<%= f.input :report, :input_html => {:style => 'height:320px;'}%>
			<center><%= f.button :submit, :class => 'button_one'  %></center>
	<% end %>
</div>

app/views/reports/new.html.erb
<div class="new-report-form">
	<center><p class="new_patient_text">New Report</p></center>
	<%= render 'form' %>
</div>

app/views/reports/show.html.erb
<div class="report_info">
	<h4>Patient Name:</h4>
	<h5><%= @report.patient.fname %> <%= @report.patient.lname %></h5>
	<h4>Condition: </h4>
	<h5><%= @report.patient.condition.name %></h5>
	<h4>BloodType:</h4>
	<h5><%= @report.patient.bloodtype %></h5>
	<h4>Date of Birth:</h4>
	<h5><%= @report.patient.dob %></h5>
	<h4>Address:</h4>
	<h5><%= @report.patient.address %></h5>
	<br>
	
</div>
<div class="report_text"> 
	<h4>Date: <%= @report.date %></h4>
	<h4><%= @report.report %></h4>
	<center>
		<%= link_to "Back", patient_path(@report.patient),class: "button_one" %>
		<% if doctor_signed_in? %>
			<% if @report.doctor_id == current_doctor.id %>
				<%= link_to "Edit", edit_patient_report_path(@report.patient_id,@report),class: "button_one" %>
				<%= link_to "Delete", patient_report_path(@report.patient_id,@report), method: :delete, data: {confirm: "Are you sure?"},class: "button_one" %>
			<% end %>
		<% end %>
	</center>
</div>